export const INITIAL_STATE = 'INITIAL_STATE';

export const FETCH_COLORS = 'FETCH_COLORS';
export const RECIEVE_COLORS = 'RECIEVE_COLORS';

export const FETCH_EVENTS = 'FETCH_EVENTS';
export const RECIEVE_EVENTS = 'RECIEVE_EVENTS';
